### ISSUE TITLE
[Bug]: Perspective Editor is not working

### ISSUE THREAD

**Issue by JTcweinrich** [pimcore/perspective-editor#101] opened 2022-10-27 11:08 UTC
### Expected behavior

it should be possible to edit own perspectives and edit the Views via the editor and create new perspectives and views

### Actual behavior

old perspectives show in tree but are not editable, if a new views is created, this is not editable either
we tested on 2 own instances and on the pimcore demo system, i all three cases we found the same wrong behaviour

### Steps to reproduce

open perspective editor an try to create a new perspective and view - its possible to add but without the possibility to edit

**Comment by mcop1** [comment] 2022-10-27 11:17
@JTcweinrich Moved the issue to the correct repository. Seems to be a duplicate of https://github.com/pimcore/perspective-editor/issues/100, there will be a fix for that today.

**Comment by mcop1** [comment] 2022-10-28 07:05
Hello @JTcweinrich ,
just had a look at the enterprise demo and it should be working again (with the latest release from yesterday).

**Closed as completed by mcop1** 2022-10-28 07:05 UTC
Labels: Bug
